// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJDlujZSTHTkZKA_Ar0gJN4qA-MGmLFMY',
    appId: '1:518279335908:web:6e4a964a7f0c9a3f8bc1f1',
    messagingSenderId: '518279335908',
    projectId: 'ratefit-8df99',
    authDomain: 'ratefit-8df99.firebaseapp.com',
    storageBucket: 'ratefit-8df99.appspot.com',
    measurementId: 'G-2EBH6VVS0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk0clZvgRODmVfVu9LBp3DIZdJyiNHx0Q',
    appId: '1:518279335908:android:bd33be11d51ebc538bc1f1',
    messagingSenderId: '518279335908',
    projectId: 'ratefit-8df99',
    storageBucket: 'ratefit-8df99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgnQlsQv382l75WZSHqo3DfmTRw9sX2zU',
    appId: '1:518279335908:ios:504b7e452d38a2a48bc1f1',
    messagingSenderId: '518279335908',
    projectId: 'ratefit-8df99',
    storageBucket: 'ratefit-8df99.appspot.com',
    iosBundleId: 'com.ratefit.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgnQlsQv382l75WZSHqo3DfmTRw9sX2zU',
    appId: '1:518279335908:ios:504b7e452d38a2a48bc1f1',
    messagingSenderId: '518279335908',
    projectId: 'ratefit-8df99',
    storageBucket: 'ratefit-8df99.appspot.com',
    iosBundleId: 'com.ratefit.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJDlujZSTHTkZKA_Ar0gJN4qA-MGmLFMY',
    appId: '1:518279335908:web:27f8243b1de59bac8bc1f1',
    messagingSenderId: '518279335908',
    projectId: 'ratefit-8df99',
    authDomain: 'ratefit-8df99.firebaseapp.com',
    storageBucket: 'ratefit-8df99.appspot.com',
    measurementId: 'G-6K4GJJLLTK',
  );
}
